INSERT INTO burgers (name, devoured) VALUES ('Single') ;
INSERT INTO burgers (name) VALUES ('Double') ;
INSERT INTO burgers (name, devoured) VALUES ('Bacon') ;
INSERT INTO burgers (name) VALUES ('Double Bacon') ;
INSERT INTO burgers (name, devoured) VALUES ('Single Cheese') ;
INSERT INTO burgers (name) VALUES ('Double Cheese') ;
INSERT INTO burgers (name, devoured) VALUES ('Mushroom&Swiss') ;
INSERT INTO burgers (name) VALUES ('Frisco') ;
INSERT INTO burgers (name, devoured) VALUES ('Veggie') ;
INSERT INTO burgers (name) VALUES ('Kids') ;